name: Deploy SSH
on:
  #push:
  #  branches:
  #    - main
  # 手動実行
  workflow_dispatch:
jobs:
  deploy-ssh:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/appleboy/ssh-action
      - name: Executing Remote SSH Commands Using SSH Key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host    : ${{ secrets.SSH_HOST }}
          port    : ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key     : ${{ secrets.SSH_KEY }}
          script  : ${{ secrets.SSH_SCRIPT }}
